<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PeriodesSeeder extends Seeder
{
    public function run(): void
    {
        $periodes = [
            [
                'id' => 1,
                'titre' => 'Choix des binômes',
                'description' => 'Formation des binômes étudiants.',
                'date_debut' => '2025-09-21',
                'date_fin' => '2025-11-22',
                'created_at' => null,
                'updated_at' => '2025-10-03 13:42:36',
                'dashboard_title' => 'etudiant£Formation des binômes$enseignant£Formation des binômes étudiants$entreprise£Formation des binômes étudiants',
                'dashboard_description' => 'etudiant£Formez votre binôme pour le projet de fin d\'études.$enseignant£Les étudiants sont en train de former leurs binômes.$entreprise£Les étudiants forment actuellement leurs binômes.',
                'dashboard_button' => 'etudiant£Associer un binôme£binome',
            ],
            [
                'id' => 2,
                'titre' => 'Proposition des thèmes',
                'description' => 'Soumission des thèmes par étudiants, enseignants et entreprises.',
                'date_debut' => '2025-11-07',
                'date_fin' => '2025-12-01',
                'created_at' => null,
                'updated_at' => '2025-01-20 09:36:56',
                'dashboard_title' => 'etudiant£Proposition de thèmes$enseignant£Proposition de thèmes$entreprise£Proposition de thèmes',
                'dashboard_description' => 'etudiant£Soumettez vos idées de projets.$enseignant£Période de soumission des thèmes pour les projets de fin d\'étude.$entreprise£Soumettez vos propositions de stages.',
                'dashboard_button' => 'etudiant£Proposer un thème£proposition-etudiant$enseignant£Mes propositions£propositions$entreprise£Mes propositions£proposition-entreprise',
            ],
            [
                'id' => 3,
                'titre' => 'Validation des thèmes',
                'description' => 'Validation ou refus des thèmes proposés par le responsable.',
                'date_debut' => '2025-12-04',
                'date_fin' => '2026-01-12',
                'created_at' => null,
                'updated_at' => '2024-12-24 10:29:41',
                'dashboard_title' => 'etudiant£Validation en cours$responsable£Validation en cours$enseignant£Validation des thèmes$entreprise£Validation en cours',
                'dashboard_description' => 'etudiant£Vos propositions sont en cours de validation.$responsable£La phase de validation des thèmes proposés par les étudiants, enseignants et entreprises commence. Vous pouvez valider ou refuser les thèmes.$enseignant£Les responsables valident actuellement les thèmes proposés.$entreprise£Vos propositions sont en cours de validation.',
                'dashboard_button' => 'responsable£Valider les thèmes£validation-propositions',
            ],
            [
                'id' => 4,
                'titre' => 'Fiches de vœux des étudiants (Groupes non acceptés)',
                'description' => 'Annonce des résultats de validation des thèmes et remplissage des fiches de vœux : groupes non acceptés (choix des idées des enseignants).',
                'date_debut' => '2026-01-11',
                'date_fin' => '2026-02-12',
                'created_at' => null,
                'updated_at' => '2024-12-24 10:30:35',
                'dashboard_title' => 'etudiant£Fiches de vœux$enseignant£Résultats de validation$entreprise£Résultats de validation',
                'dashboard_description' => 'etudiant£Remplissez votre fiche de vœux pour choisir parmi les idées des enseignants et entreprises.$enseignant£Consulter les résultats de validation.$entreprise£Consulter les résultats de validation.',
                'dashboard_button' => 'etudiant£Remplir ma fiche£choix-pfe',
            ],
            [
                'id' => 5,
                'titre' => 'Résultats et fiche de vœux enseignants',
                'description' => 'Les étudiants reçoivent les résultats de leurs fiches de voeux et les enseignants remplissent une fiche de vœux pour indiquer leurs préférences concernant les idées proposées par les étudiants et les groupes qui ont comme PFE un stage.',
                'date_debut' => '2026-01-01',
                'date_fin' => '2027-01-22',
                'created_at' => null,
                'updated_at' => null,
                'dashboard_title' => 'etudiant£Résultats des fiches$enseignant£Fiche de vœux enseignants$entreprise£Suivi des affectations',
                'dashboard_description' => 'etudiant£Consultez les résultats de vos fiches de vœux.$enseignant£Remplissez votre fiche de vœux pour les pfe concernant les idées proposées par les étudiants et les groupes qui ont comme pfe un stage.$entreprise£Les étudiants reçoivent les résultats de leurs fiches de voeux et les enseignants sont en train de choisir les groups à encadrer.',
                'dashboard_button' => 'enseignant£Encadrer un PFE£choix-pfe-enseignant',
            ],
            [
                'id' => 6,
                'titre' => 'Résultats des fiches de vœux',
                'description' => 'Annonce des résultats des fiches de vœux pour les enseignants et notifier les etudiants des résultats.',
                'date_debut' => '2026-01-01',
                'date_fin' => '2027-01-22',
                'created_at' => null,
                'updated_at' => '2024-12-24 10:31:49',
                'dashboard_title' => 'etudiant£Période de réalisation des PFE$enseignant£Période de réalisation des PFE$entreprise£Période de réalisation des PFE',
                'dashboard_description' => 'etudiant£Vous pouvez consulter votre affectation finale. Cette période est consacrée à la mise en œuvre de l\'ensemble des projets de fin d\'études.$enseignant£Consultez les résultats des affectations. Cette période est consacrée à la mise en œuvre de l\'ensemble des projets de fin d\'études.$entreprise£Consultez les groupes qui vous sont affectés. Cette période est consacrée à la mise en œuvre de l\'ensemble des projets de fin d\'études.',
                'dashboard_button' => 'etudiant£Calendrier£calendrier$enseignant£Calendrier£calendrier$entreprise£Calendrier£calendrier',
            ],
            [
                'id' => 7,
                'titre' => 'Décision de la session',
                'description' => 'Décision du groupe pour chaque session de soutenance, en lien avec les encadrants.',
                'date_debut' => '2026-01-01',
                'date_fin' => '2027-01-11',
                'created_at' => null,
                'updated_at' => '2024-12-24 10:32:23',
                'dashboard_title' => 'etudiant£Session de soutenance$enseignant£Décision des sessions$entreprise£Sessions de soutenance',
                'dashboard_description' => 'etudiant£Discutez avec votre encadrant afin de confirmer si vous passez en session 1 ou en session 2.$enseignant£Participez à la décision des sessions avec les groupes.$entreprise£Attribution des sessions en cours par les encadrants.',
                'dashboard_button' => 'enseignant£Gérer les sessions£sessions',
            ],
            [
                'id' => 8,
                'titre' => 'Fiche de vœux des Enseignants pour la Composition du Jury',
                'description' => 'Les enseignants remplissent une fiche de vœux pour exprimer leur désir de faire partie du jury.',
                'date_debut' => '2026-01-01',
                'date_fin' => '2027-01-22',
                'created_at' => null,
                'updated_at' => null,
                'dashboard_title' => 'etudiant£Composition du jury$enseignant£Fiche de vœux jury$entreprise£Composition du jury',
                'dashboard_description' => 'etudiant£Le jury de votre soutenance est en cours de formation.$enseignant£Exprimez votre souhait de faire partie du jury.$entreprise£Les jury des soutenances est en cours de formation.',
                'dashboard_button' => 'enseignant£Candidature jury£fiche-jury',
            ],
            [
                'id' => 9,
                'titre' => 'Résultats des Fiches de Vœux des Enseignants pour le Jury',
                'description' => 'Les résultats des fiches de vœux des enseignants pour le jury ont permis d\'affecter les membres du jury.',
                'date_debut' => '2026-01-01',
                'date_fin' => '2027-01-22',
                'created_at' => null,
                'updated_at' => null,
                'dashboard_title' => 'etudiant£Jury constitué$enseignant£Affectations jury$entreprise£Jury constitué',
                'dashboard_description' => 'etudiant£Le jury de votre soutenance a été constitué.$enseignant£Consultez vos affectations dans les jurys.$entreprise£Les jurys des soutenances ont été constitués.',
                'dashboard_button' => '',
            ],
            [
                'id' => 10,
                'titre' => 'La planification des soutenances',
                'description' => 'Le système planifie automatiquement les soutenances, et l\'administrateur peut les ajuster selon les besoins.',
                'date_debut' => '2026-01-01',
                'date_fin' => '2027-01-22',
                'created_at' => null,
                'updated_at' => null,
                'dashboard_title' => 'etudiant£Planification des soutenances$enseignant£Planification des soutenances$entreprise£Planification des soutenances',
                'dashboard_description' => 'etudiant£Votre soutenance est en cours de planification.$enseignant£Les soutenances sont en cours de planification.$entreprise£Les soutenances sont en cours de planification.',
                'dashboard_button' => '',
            ],
            [
                'id' => 11,
                'titre' => 'Soutenances : Session 1',
                'description' => 'Période dédiée aux soutenances des projets, Session 1.',
                'date_debut' => '2026-04-30',
                'date_fin' => '2027-05-20',
                'created_at' => null,
                'updated_at' => '2024-12-24 14:30:34',
                'dashboard_title' => 'etudiant£Soutenances Session 1$enseignant£Soutenances Session 1$entreprise£Soutenances Session 1',
                'dashboard_description' => 'etudiant£La première session des soutenances est actuellement en cours.$enseignant£La première session des soutenances est actuellement en cours.$entreprise£La première session des soutenances est actuellement en cours.',
                'dashboard_button' => 'etudiant£Calendrier£calendrier$enseignant£Calendrier£calendrier$entreprise£Calendrier£calendrier',
            ],
            [
                'id' => 12,
                'titre' => 'Soutenances : Session 2',
                'description' => 'Période dédiée aux soutenances des projets, Session 2.',
                'date_debut' => '2026-04-13',
                'date_fin' => '2027-09-20',
                'created_at' => null,
                'updated_at' => '2025-07-16 18:27:49',
                'dashboard_title' => 'etudiant£Soutenances Session 2$enseignant£Soutenances Session 2$entreprise£Soutenances Session 2',
                'dashboard_description' => 'etudiant£La deuxième session des soutenances est actuellement en cours.$enseignant£La deuxième session des soutenances est actuellement en cours.$entreprise£La deuxième session des soutenances est actuellement en cours.',
                'dashboard_button' => 'etudiant£Calendrier£calendrier$enseignant£Calendrier£calendrier$entreprise£Calendrier£calendrier',
            ],
            [
                'id' => 13,
                'titre' => 'Attribution des Notes Finales',
                'description' => 'Après les soutenances, les jurys et les encadrants évaluent les performances des étudiants et attribuent leurs notes. À la fin de cette phase, les étudiants reçoivent leurs résultats finaux.',
                'date_debut' => '2026-01-01',
                'date_fin' => '2027-06-23',
                'created_at' => null,
                'updated_at' => '2025-07-16 19:21:52',
                'dashboard_title' => 'etudiant£Votre évaluation est en cours$enseignant£Évaluation finale$entreprise£Résultats finaux',
                'dashboard_description' => 'etudiant£Vos notes sont actuellement en cours de traitement.$enseignant£Attribuez les notes finales des étudiants.$entreprise£Les performances des étudiants sont actuellement évaluées et les notes sont en cours de finalisation.',
                'dashboard_button' => 'enseignant£Évaluer£note-enseignant',
            ],
        ];

        DB::table('periodes')->insert($periodes);
    }
}