<?php

namespace App\Enums;

enum NotificationType: string
{
    case SYSTEM = 'SYSTEM';
    case MESSAGE = 'MESSAGE';
    case EVENT = 'EVENT';
    case ALERT = 'ALERT';
    case REMINDER = 'REMINDER';
    case CO_SUPERVISION = 'CO_SUPERVISION';
    case GROUP_INVITATION = 'GROUP_INVITATION';
    case EMAIL_AUTOMATION_UPDATE = 'EMAIL_AUTOMATION_UPDATE';
    case EMAIL_AUTOMATION_STATUS_UPDATE = 'EMAIL_AUTOMATION_STATUS_UPDATE';
    case PFE_VALIDATION = 'PFE_VALIDATION';
    case EMAIL_NOTIFICATION = 'EMAIL_NOTIFICATION';
    case SOUTENANCE_GENERATION = 'SOUTENANCE_GENERATION';
}